version: '3.8'

services:
  mysql:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: temp_pass
      MYSQL_DATABASE: django_database
      MYSQL_USER: temp_user
      MYSQL_PASSWORD: temp_pass
    networks:
      - mynetwork
  
  backend:
    image: backend
    build: ../backend/deploy
    restart: always
    ports:
      - "8000:80"
    depends_on:
      - "mysql"
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_DATABASE=django_database
      - MYSQL_USER=temp_user
      - MYSQL_PASSWORD=temp_pass
    networks:
      - mynetwork
    healthcheck:
      test: ["CMD", "/bin/bash", "-c", "dockerize -wait tcp://mysql:3306 -timeout 10s"]
      interval: 30s
      timeout: 31s
      retries: 3
      start_period: 1s

  frontend:
    image: frontend
    build: ../frontend/deploy
    restart: always
    ports:
      - "8080:80"
    depends_on:
      - "backend"
    links:
      - "backend"
    networks:
      - mynetwork
    healthcheck:
      test: ["CMD", "/bin/bash", "-c", "dockerize -wait tcp://backend:80 -timeout 10s"]
      interval: 30s
      timeout: 31s
      retries: 3
      start_period: 1s

networks:
  mynetwork:
    driver: bridge